name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libs
      run: sudo apt-get update && sudo apt-get install libmagick++-dev
    - name: Go to repo
      run: cd Pure_cpp
    - name: Compile
      run: c++ -o converter main.cpp `Magick++-config --cppflags --cxxflags --ldflags --libs`   
      

